---

- name: install vcsh
  apt: pkg=vcsh state=present

- name: clone vcsh repos
  command: vcsh clone https://github.com/alourie/vcsh-{{item}}.git {{item}}
  sudo: false
  with_items:
     - vim
     - zsh

