---
# the host in which the playbook will be run
- hosts: localhost
  # in this example, we using a localhost, so this is needed
  connection: local

  # the target user Ansible will impersonate when provisioning
  user: alourie

  # this makes all tasks run with sudo by default
  sudo: true

  # additional variables
  vars:
    user: alourie
    vim_base: vim-gtk

  tasks:
      - name: Install dependencies
        apt: pkg={{item}} state=present
        with_items:
            - python-pycurl
            - python-apt

      - name: Install Galaxy modules
        command: ansible-galaxy install {{item}}
        with_items:
            - Ansibles.apt
            - Ansibles.vim
            - Ansibles.build-essential
            - Ansibles.python
            - devbox.oh-my-zsh
            - devbox.chrome

      - include: mybook.yml
