---
# the host in which the playbook will be run
- hosts: localhost
  # in this example, we using a localhost, so this is needed
  connection: local

  # the target user Ansible will impersonate when provisioning
  user: alourie

  # this makes all tasks run with sudo by default
  sudo: true

  # additional variables
  vars:
    user: alourie

  # roles are a way to group tasks; they will run in the sequence determined here
  roles:
    - Ansibles.git
    - Ansibles.vim vim_base=vim-gtk
    - Ansibles.build-essential ansible_os_family=Debian
    - Ansibles.python
    - devbox.oh-my-zsh
