---
# the host in which the playbook will be run
- hosts: localhost
  # in this example, we using a localhost, so this is needed
  connection: local

  # the target user Ansible will impersonate when provisioning
  user: alourie

  # this makes all tasks run with sudo by default
  sudo: true

  # additional variables
  vars:
    user: alourie
    vim_base: vim-gtk
    ansible_os_family: Debian

  # roles are a way to group tasks; they will run in the sequence determined here
  roles:
    - Ansibles.apt
    - Ansibles.vim
    - Ansibles.build-essential
    - Ansibles.python
    - devbox.oh-my-zsh
    - devbox.chrome
    - devbox.vcsh
    - devbox.custom_vim
